export class Activity {
    id: string;
    athlete: { id: string; resource_state: number };
    achievement_count: number;
    athlete_count: number;
    average_speed: number;
    comment_count: number;
    commute: boolean;
    distance: number;
    elapsed_time: number;
    elev_high: number;
    elev_low: number;
    end_latlng: [number, number];
    external_id: string;
    flagged: boolean;
    from_accepted_tag: boolean;
    gear_id: number;
    has_heartrate: boolean;
    has_kudoed: boolean;
    kudos_count: number;
    location_city: null;
    location_country: null;
    location_state: null;
    manual: false;
    map: {
        id: string;
        summary_polyline: string;
        resource_state: number;
    };
    max_speed: number;
    moving_time: number;
    name: string;
    photo_count: number;
    pr_count: number;
    private: false;
    resource_state: number;
    start_date: Date;
    start_date_local: string;
    start_latitude: number;
    start_latlng: [number, number];
    start_longitude: number;
    timezone: string;
    total_elevation_gain: number;
    total_photo_count: number;
    trainer: boolean;
    type: 'Run' | 'Ride' | 'Swim';
    upload_id: number;
    utc_offset: number;
    visibility: string;
    windowPosition: number;
    workout_type: number;
}
